name: Docker build

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login into Dockerhub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username=${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
      - name: Pull latest Docker image
        run: docker pull fictionaldev/tick-take-api:latest
      - name: Build the Docker image
        run: docker build --cache-from fictionaldev/tick-take-api:latest -t fictionaldev/tick-take-api .
      - name: Push docker image
        run: docker push fictionaldev/tick-take-api
      - name: Connect to server and update a container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "${{ secrets.ENV }}" > .env.example
            docker pull fictionaldev/tick-take-api
            docker container stop tick-take-api || true
            docker container rm tick-take-api || true
            docker run --env-file=.env.example --name tick-take-api -d -p 80:5001 fictionaldev/tick-take-api
            rm .env.example
