name: Docker build

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  RUN_REGION: europe-west1
  SERVICE_NAME: tick-take-api

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY}}
      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID
      # Build and push image to Google Container Registry
      - name: Build
        run: |
          gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME
      # Deploy image to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy $SERVICE_NAME \
            --region $RUN_REGION \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
            --platform managed \
            --set-env-vars "ACCESS_TOKEN_SECRET=${{ secrets.ENV_ACCESS_TOKEN_SECRET }},CLIENT_ORIGIN=${{ secrets.ENV_CLIENT_ORIGIN }},DB_NAME=${{ secrets.ENV_DB_NAME }},DB_URL=${{ secrets.ENV_DB_URL }},DB_SALT=${{ secrets.ENV_DB_SALT }}"
